version: '3'

services:
  db:
    build:
      context: ./db
      dockerfile: ./Dockerfile
      args:
        DB_DATABASE: "book"
        DB_USERNAME: "exxea"
        DB_PASSWORD: "password"
        DB_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    networks:
      my_network:
        ipv4_address: 172.63.1.2

  php:
    build:
      context: ./php
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./php/app/:/usr/src/app
    networks:
      my_network:
        ipv4_address: 172.63.1.1

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.63.0.0/16